#!/usr/bin/env bash
# Git aliases and etc.
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2012-06-13
# Requires: bpm.defaults
################################################################################

bash_plugin_login() {
    bash_default_alias g    "git status"
    bash_default_alias gd   "git diff"
    bash_default_alias gdc  "git diff --cached"
    bash_default_alias gD   "git diff HEAD"
    bash_default_alias ga   "git add"
    bash_default_alias gau  "git add -u"
    bash_default_alias gl   "git log --decorate --graph"
    bash_default_alias gb   "git branch -v"
    bash_default_alias gc   "git checkout"
    bash_default_alias gri  "git rebase -i"
    bash_default_alias gru  "git remote update"
    # launch Vim with fugitive :Gstatus
    bash_default_alias gg   'vim +Gstatus +only "$PWD"'
}
