#!/usr/bin/env bash
# Make tmux use the current working directory when creating a new window
# 
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-05-13
# See-Also: http://unix.stackexchange.com/questions/12032/create-new-window-with-current-directory-in-tmux
# Requires: bpm.prompt-hooks
################################################################################

bash_plugin_login() {
    if [ -n "$TMUX" ]; then
        -tmux-sync-default-path() {
            tmux set default-path "$PWD" |:
        }
        bash_insert_chpwd -tmux-sync-default-path
    fi
}
