#!/usr/bin/env bash
# Make tmux reflect the name of current working directory on window title
# 
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2013-05-13
# See-Also: http://www.commandlinefu.com/commands/view/10046/automatically-rename-tmux-window-using-the-current-working-directory 
# Requires: bpm.events
################################################################################

bash_plugin_login() {
    if [ -n "$TMUX" ]; then
        -tmux-cwd-title-update() {
            local title="${PWD##*/}"
            case $PWD in
                "$HOME") # home
                    title= ;;
                /) # root
                    title="/" ;;
            esac
            if [ -n "$title" ]; then
                tmux rename-window "$title"
            else
                tmux set-window-option automatic-rename on
            fi | cat >/dev/null # XXX tmux hangs without cat, -q is only available >= 1.7
        }
        bash_add_chpwd -tmux-cwd-title-update
    fi
}
